"""Repository layer — SQLite persistence.

Public API re-exported here so callers import from newsprism.repo,
not newsprism.repo.db, keeping the internal layout flexible.
"""
from newsprism.repo.db import (
    DB_PATH,
    delete_clusters_for_date,
    get_articles_by_ids,
    get_article_id_by_url,
    get_calibration_weights,
    get_latest_editorial_policy,
    get_report_article_ids,
    get_clusters_for_date,
    get_recent_clusters,
    get_unclustered_articles,
    init_db,
    insert_article,
    insert_cluster,
    insert_cluster_evaluation,
    insert_cluster_quality_report,
    insert_search_request_event,
    link_cluster_evaluation,
    mark_articles_clustered,
    reset_articles_clustered,
    seed_calibration_weights,
    update_article_embedding,
    upsert_storyline_state,
)

__all__ = [
    "DB_PATH",
    "init_db",
    "delete_clusters_for_date",
    "insert_article",
    "get_article_id_by_url",
    "get_unclustered_articles",
    "get_articles_by_ids",
    "get_report_article_ids",
    "get_recent_clusters",
    "mark_articles_clustered",
    "update_article_embedding",
    "insert_cluster",
    "insert_cluster_evaluation",
    "insert_cluster_quality_report",
    "insert_search_request_event",
    "link_cluster_evaluation",
    "get_calibration_weights",
    "get_latest_editorial_policy",
    "seed_calibration_weights",
    "upsert_storyline_state",
    "get_clusters_for_date",
    "reset_articles_clustered",
]
